services:
  hello_sdl:
    devices:
      - /dev/dxg

    environment:
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir

    volumes:
      - /mnt/wslg/runtime-dir/${WAYLAND_DISPLAY}:/mnt/wslg/runtime-dir/${WAYLAND_DISPLAY}
